### ISSUE TITLE
Для чего нужна вкладка GAopener?

### ISSUE THREAD

**Issue by lmiol** [Yur0K/SteamKeysManager#8]
Оч крутое приложение, но для чего нужна вкладка GAopener?
Если хо можем посотрудничать и я вкину фич для улучшения приложения (я работаю QA/UX)

**Comment by Yur0K** [comment]
@lmiol Привет, приложение писал для себя изначально, чисто как базу данных ключей, но потом решил залить сюда. Вкладка GAopener используется для быстрого открытия портативных браузеров ботов для получения ключей с раздач (чтобы не копипастить ссылки, просто вставляем их туда один раз, выбираем бота и открываем). Если есть какие то идеи и реализации, можешь кидать PRы, буду благодарен)
Я не силён в программировании, как можешь видеть по коду. И, кстати, тоже работаю как QA engineer)
